//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.MEMBERs = new HashSet<MEMBER>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public int course_submit_day { get; set; }
        public System.DateTime course_date_created { get; set; }
        public System.DateTime course_begin_date { get; set; }
        public System.DateTime course_end_date { get; set; }
        public short course_is_enabled { get; set; }
        public Nullable<double> course_ref_grade { get; set; }
        public Nullable<double> course_ref_hours { get; set; }
    
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
    }
}
