//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using _14_TimeMachine2.Models;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.MEMBERs = new HashSet<MEMBER>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
        [Key]
        public int course_id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "Max 50 digits")]
        [Display(Name = "Course Name")]
        public string course_name { get; set; }
        [Required]
        [Display(Name = "Submit Day")]
        public int course_submit_day { get; set; }
        [Required]
        [Display(Name = "Date Created")]
        [DataType(DataType.DateTime)]
        public System.DateTime course_date_created { get; set; }
        [Required]
        [Display(Name = "Begin Date")]
        [DataType(DataType.Date)]
        public System.DateTime course_begin_date { get; set; }
        [Required]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public System.DateTime course_end_date { get; set; }
        [Required]
        [Display(Name = "Enabled?")]
        public short course_is_enabled { get; set; }
        [Required]
        [Display(Name = "Grade")]
        public Nullable<double> course_ref_grade { get; set; }
        [Required]
        [Display(Name = "Hours")]
        public Nullable<double> course_ref_hours { get; set; }
    
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
        public virtual ICollection<PROJECT> PROJECTs { get; set; }

        // ryoder [start]
        public bool is_enabled()
        {
            return (this.course_is_enabled == 1);
        }

        public void toggle_status()
        {
            this.course_is_enabled = (short)(this.course_is_enabled ^ 1);
            return;
        }

        public List<USER> getStudentsForCourse()
        {
            List<USER> studentList = new List<USER>();
            TM2Entities2 db = new TM2Entities2();

            foreach (MEMBER m in this.MEMBERs)
            {
                USER temp = db.USERs.Find(m.member_user_id);
                if (temp.is_student())
                    studentList.Add(temp);
            }

            return studentList;
        }

        public USER getTeacherForCourse()
        {
            USER teacher = new USER();
            USER temp;
            TM2Entities2 db = new TM2Entities2();

            foreach (MEMBER m in this.MEMBERs)
            {
                if ((temp = db.USERs.Find(m.member_user_id)).is_teacher())
                    teacher = temp;
            }

            return teacher;
        }

        public DateTime getRelativeStartTime()
        {
            // Calculate extra days at the beginning of the semester. 
            // Add 1 to the submit day to move its boundary to the end of the day.
            int extraDays = this.course_submit_day + 1 - (int)this.course_begin_date.DayOfWeek;
            if (extraDays < 0)
                extraDays += 7;
            return this.course_begin_date.AddDays(extraDays);
        }

        public int getLastEntryWeek()
        {
            Double lastEntryDay = ((DateTime)this.course_end_date - this.getRelativeStartTime()).TotalDays;
            return (int)Math.Floor(lastEntryDay / 7.0);
        }

        public int getLatestWeek()
        {
            DateTime relStartDay = this.getRelativeStartTime();
            int lastEntryWeek = this.getLastEntryWeek();

            double currentDay = (DateTime.Today - relStartDay).TotalDays;
            int latestWeek = (int)Math.Floor(currentDay / 7.0) + 1;
            if (currentDay < 0.0) latestWeek = 1;
            if (latestWeek > lastEntryWeek) latestWeek = lastEntryWeek;

            return latestWeek;
        }

        public DateTime getLatestDay()
        {
            return DateTime.Now < this.course_end_date ? DateTime.Now : this.course_end_date;
        }
        // ryoder [end]
    }
}
