//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TM2Entities2 : DbContext
    {
        public TM2Entities2()
            : base("name=TM2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORY> CATEGORies { get; set; }
        public DbSet<COURSE> COURSEs { get; set; }
        public DbSet<ENTRY> ENTRies { get; set; }
        public DbSet<LOCATION> LOCATIONs { get; set; }
        public DbSet<MEMBER> MEMBERs { get; set; }
        public DbSet<PROJECT> PROJECTs { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<class_summary> class_summary { get; set; }
    }
}
