//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ENTRies = new HashSet<ENTRY>();
            this.MEMBERs = new HashSet<MEMBER>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public string user_id { get; set; }
        public Nullable<short> user_is_enabled { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public Nullable<short> user_is_student { get; set; }
        public Nullable<short> user_is_teacher { get; set; }
        public Nullable<short> user_is_manager { get; set; }
    
        public virtual ICollection<ENTRY> ENTRies { get; set; }
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
        public virtual ICollection<PROJECT> PROJECTs { get; set; }

        // ryoder [start]
        public bool is_enabled()
        {
            return (this.user_is_enabled == 1);
        }

        public bool is_student()
        {
            return (this.user_is_student == 1);
        }

        public bool is_teacher()
        {
            return (this.user_is_teacher == 1);
        }

        public bool is_manager()
        {
            return (this.user_is_manager == 1);
        }

        public void toggle_status()
        {
            this.user_is_enabled = (Int16)(this.user_is_enabled ^ 1);
            return;
        }
        // ryoder [end]
    }
}
