//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public string member_user_id { get; set; }
        public int member_course_id { get; set; }
        public string member_position { get; set; }
        public Nullable<System.DateTime> member_is_enabled { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
