//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_summary
    {
        public int course_id { get; set; }
        public string user_id { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> HoursDay { get; set; }
        public Nullable<int> HoursWeek { get; set; }
        public Nullable<double> ProjectedGrade { get; set; }
    }
}
