//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.MEMBERs = new HashSet<MEMBER>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public int course_submit_day { get; set; }
        public System.DateTime course_date_created { get; set; }
        public System.DateTime course_begin_date { get; set; }
        public System.DateTime course_end_date { get; set; }
        public short course_is_enabled { get; set; }
        public Nullable<double> course_ref_grade { get; set; }
        public Nullable<double> course_ref_hours { get; set; }
    
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
        public virtual ICollection<PROJECT> PROJECTs { get; set; }

        public List<USER> getStudentsForCourse()
        {
            List<USER> studentList = new List<USER>();
            TM2Entities2 db = new TM2Entities2();

            foreach (MEMBER m in this.MEMBERs)
            {
                USER temp = db.USERs.Find(m.member_user_id);
                if (temp.is_student())
                    studentList.Add(temp);
            }

            return studentList;
        }

        public USER getTeacherForCourse()
        {
            USER teacher = new USER();
            USER temp;
            TM2Entities2 db = new TM2Entities2();

            foreach (MEMBER m in this.MEMBERs)
            {
                if ((temp = db.USERs.Find(m.member_user_id)).is_teacher())
                    teacher = temp;
            }

            return teacher;
        }
    }
}
