//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public int course_id { get; set; }
        public string course_name { get; set; }
        public Nullable<int> course_submit_day { get; set; }
        public Nullable<System.DateTime> course_date_created { get; set; }
        public Nullable<System.DateTime> course_begin_date { get; set; }
        public Nullable<System.DateTime> course_end_date { get; set; }
    }
}
