//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_TimeMachine2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.ENTRies = new HashSet<ENTRY>();
        }
    
        public int location_id { get; set; }
        [Display(Name = "Location")]
        public string location_name { get; set; }
        public Nullable<short> location_is_enabled { get; set; }
        public Nullable<int> location_created_by { get; set; }
        public Nullable<System.DateTime> location_date_created { get; set; }
    
        public virtual ICollection<ENTRY> ENTRies { get; set; }
    }
}
